version: '3.3'

services:
  api:
    container_name: backend
    restart: on-failure
    build: ./backend
    volumes:
      - type: bind
        source: ./backend/result-2.db
        target: /opt/database/result-2.db
    ports:
      - 8080:8080
  web:
    container_name: frontend
    restart: on-failure
    build: ./frontend
    stdin_open: true
    environment: 
      - NODE_ENV=production
    ports: 
      - 3000:3000
    depends_on: 
      - api
    links: 
      - api
