version: '3.7'

services:
  api:
    restart: on-failure
    build: ./backend
    container_name: backend
    volumes:
      - type: bind
        source: ./backend/result-2.db
        target: /opt/database/result-2.db
    ports:
      - 8080:8080
      - 20:20
  web:
    restart: on-failure
    build: ./frontend
    container_name: frontend
    ports: 
      - 3000:3000
