name: CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CI_SERVER_IP }}
          username: ${{ secrets.CI_SERVER_USER }}
          key: ${{ secrets.CI_SERVER_SECRET }}
          script: |
            whoami
            ls -al
