# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CI_SERVER_IP }}
          username: ${{ secrets.CI_SERVER_USER }}
          key: ${{ secrets.CI_SERVER_KEY }}
          script: |
            whoami
            ls -al
