name: CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: fifsky/ssh-action@master
      with:
        command: |
          cd /tmp
          ls -a
          whoami
        host: ${{ secrets.CI_SERVER_IP }}
        user: root
        key: ${{ secrets.CI_SERVER_SECRET}}
